### ISSUE TITLE
geolocalization is null

### ISSUE THREAD

**Issue by YeisonVelez11** [jeffreymorganio/twitter-geo-server-js#1]
I am trying to filter the tweets coming from my country, with the word "andino", the tweets  will come from Colombia. But in the information the tweets that I receive with the keys of "coordinates", "place" are null. How can I get the geolocation of the tweets?

With the current code, I made the change to filter the tweets with the word "andino", making the following change:
line 11
https://github.com/UsabilityEtc/twitter-geo-server-js/blob/master/js/twitter-connection.js

      { track: "andino" }
instead of:

     { locations: boundingBox },

**Comment by jeffreymorganio** [comment]
Hi. I will investigate your issue and post back here.

**Comment by YeisonVelez11** [comment]
I would appreciate it too. Thank you very much, I do not know how to correct it.

**Comment by jeffreymorganio** [comment]
Hi. The server will return geocoded tweets when you use `{ track: ... }` instead of `{ locations: boundingBox }`. However, the problem you are having is that there are so few tweets with both your keyword and geocoding data. This is because only a small percentage of all tweets have geocoding data.

When sampling with `{ locations: boundingBox }`, all of the tweets will have geocoding information. When sampling with `{ track: ... }` all of the tweets will contain the tracked keyword but only a small number of those will have geocoding data. If you keep the server running you may eventually see some geocoded tweets with your keyword.

If you are interested in all geocoded tweets from Colombia you can filter out non-Colombian tweets by checking if the value of `coordinates.countryCode` is CO, which is the country code of Colombia.

I hope this helps.

**Comment by YeisonVelez11** [comment]
Is there another way by which I can get the location from which a tweet is made? thank you very much.

**Comment by jeffreymorganio** [comment]
Hi. If the Twitter user that authored a tweet does not allow their tweets to be geocoded then there is no way to get the exact latitude and longitude coordinates of that tweet.

There are ways to approximate a very general location by examining the locations Twitter users mention in their user profiles and using their self-identified location as a proxy for the location of their tweets.

Whether this approach will work for you depends on how fine-grained you need the location of tweets to be. Profile locations may give you the country or even the city, whereas latitude longitude will give you a street. And, of course, Twitter users don't always tweet from the location mentioned in their profile.
